# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

platform:
  - x64
  - x86

matrix:
  fast_finish: true

install:
  # Build
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 13.5.0) $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

cache:
  # local npm modules
  - 'node_modules -> package.json'
  # npm cache
  - '%APPDATA%\npm-cache'

build: off

deploy: off
